### ISSUE TITLE
Práctica 4 de Aricel, Alain, nayeli

### ISSUE THREAD

**Issue by NayeliMoraless** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-en-web-3-0-equipo-naa#1]
[Practica.4 MODEDLO CANVAS.pdf](https://github.com/user-attachments/files/17156195/Practica.4.MODEDLO.CANVAS.pdf)

**Comment by GibranVasquez** [comment]
18 Bien implementado su plan de negocio, especifica correctamente el método de Canvas, falto escoger una mejor paleta de colores

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
